name: s4d
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
  - conda-forge
  - http://192.168.0.11:2020
dependencies:
  - audioread=2.1.5=py36_0
  - bson=0.5.4=py36_0
  - flask=1.0.2=py_1
  - libzip=1.5.0=0
  - pyqt=4.11.4=py36_3
  - resampy=0.2.1=py_1
  - x264=1!152.20180717=h470a237_1
  - speakin_base_algo_agent=0.0.3=py36
  - speakin_ivector=0.0.2=py36
  - speakin_voice_feats=0.0.7=py36
  - libgfortran=3.0.0=1
  - qt=4.8.7=2
  - sip=4.18=py36_0
  - blas=1.0=mkl
  - bottleneck=1.2.1=py36h035aef0_1
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15=py36_0
  - click=7.0=py36_0
  - cycler=0.10.0=py36_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py36_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.0=118
  - itsdangerous=1.0.0=py36_0
  - jinja2=2.10=py36_0
  - joblib=0.12.5=py36_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.0.1=py36hf484d3e_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h63c8f33_5
  - libopus=1.2.1=hb9ed12e_0
  - libpng=1.6.34=hb9fc6fc_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - llvmlite=0.25.0=py36hd408876_0
  - markupsafe=1.0=py36h14c3975_1
  - mkl=2019.0=118
  - mkl-service=1.1.2=py36h90e4bf4_5
  - mkl_fft=1.0.6=py36h7dd41cf_0
  - mkl_random=1.0.1=py36h4414c95_1
  - ncurses=6.1=hf484d3e_0
  - numba=0.40.0=py36h962f231_0
  - numpy=1.15.2=py36h1d66e8a_1
  - numpy-base=1.15.2=py36h81de0dd_1
  - openssl=1.1.1=h7b6447c_0
  - pcre=8.42=h439df22_0
  - pip=10.0.1=py36_0
  - pyparsing=2.2.1=py36_0
  - python=3.6.7=h0371630_0
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.5=py36_0
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.20.0=py36h4989274_1
  - scipy=1.1.0=py36hfa4b5c9_1
  - setuptools=40.4.3=py36_0
  - six=1.11.0=py36_1
  - sqlite=3.25.2=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=5.1.1=py36h7b6447c_0
  - werkzeug=0.14.1=py36_0
  - wheel=0.32.0=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=ha838bed_2
  - pip:
    - h5py==2.8.0
    - mock==2.0.0
    - nose==1.3.7
    - pandas==0.21.1
    - pydub==0.23.0
    - pyyaml==3.13
    - sidekit==1.2.3
    - sortedcontainers==1.5.9
    - theano==1.0.3
prefix: /home/yongyu/anaconda3/envs/s4d

